# https://github.com/Ezard/semantic-prs

enabled: true

titleAndCommits: true

types:
  - feat
  - fix
  - docs
  - style
  - refactor
  - test
  - build
  - ci
  - chore
  - revert
  - deps

scopes:
  - core
  - dev
  - k8s
  - multitenancy
  - otel
