group=io.arconia
version=0.31.0-SNAPSHOT

org.gradle.configuration-cache=false
org.gradle.caching=true
org.gradle.parallel=false

org.gradle.jvmargs=-Xmx8g

datasourceMicrometerSpringBootVersion=2.2.1
doclingVersion=0.6.1
flociVersion=2.13.0
openInferenceVersion=0.1.15
openTelemetryInstrumentationVersion=2.30.0
openTelemetrySemanticConventionsVersion=1.43.0
springAiVersion=2.0.0
springCloudAwsVersion=4.1.0
