group=io.arconia
version=0.31.0-SNAPSHOT

org.gradle.configuration-cache=false
org.gradle.caching=true
org.gradle.parallel=false

org.gradle.jvmargs=-Xmx8g

datasourceMicrometerSpringBootVersion=2.3.0
doclingVersion=0.6.6
flociVersion=2.16.1
openInferenceVersion=0.1.19
openTelemetryInstrumentationVersion=2.31.1
openTelemetrySemanticConventionsVersion=1.43.0
springAiVersion=2.0.1
springCloudAwsVersion=4.1.1
testcontainersKeycloakVersion=4.3.1
