= Arconia Framework
:description: Welcome to the documentation about the Arconia Framework for Java and Spring Boot applications.

[.hero]
Welcome to Arconia Framework! This documentation will help you get started with the framework and explore its features.

== What is Arconia?

Arconia is a framework designed to build modern enterprise applications using Java and Spring Boot, emphasizing developer experience and cloud native architectures.

NOTE: The Arconia Framework is currently in active development. We're working hard to improve it and appreciate your patience as we continue to refine the tool. Feel free to try it out and share your feedback!

== Key Features

* *Developer Experience* - Support for transparent, zero-code integrations for services your application depends on, both at development and test time.
* *Multitenancy* - Support for multiple tenants across the application, including web, data, security, and configuration.
* *Observability* - Support for OpenTelemetry, bridging the gap between Spring Boot and the rest of the observability ecosystem.

== Authors

The Arconia Framework is maintained by https://thomasvitale.com[Thomas Vitale].
