= Upgrading Arconia

Arconia is currently in active development. We're working hard to improve it and appreciate your patience as we continue to refine the tool.

We're moving fast, and the APIs may change frequently, but we're committed to keeping the documentation up to date and making it easy to upgrade to the latest version.

We maintain an https://docs.openrewrite.org[OpenRewrite] recipe to help you upgrade your projects to the latest version of Arconia automatically. You can run it with the Arconia CLI, Gradle, or Maven.

== Arconia CLI

Using the https://arconia.io/docs/arconia-cli/latest/[Arconia CLI], you can upgrade your project to the latest version of Arconia:

[source,shell]
----
arconia update framework
----

Optionally, you can provide the `--to-version` flag to specify the version you want to upgrade to:

[source,shell]
----
arconia update framework --to-version 0.11.0
----

== Gradle OpenRewrite Plugin

Using the https://docs.openrewrite.org[OpenRewrite Gradle Plugin], you can apply the recipe to your project as follows.

First, create an `init.gradle` file in your Spring Boot project (root folder) with the following content:

[source,groovy]
----
initscript {
    repositories {
        maven { url "https://plugins.gradle.org/m2" }
    }
    dependencies {
        classpath("org.openrewrite:plugin:latest.release")
    }
}

rootProject {
    plugins.apply(org.openrewrite.gradle.RewritePlugin)
    dependencies {
        rewrite("io.arconia.migrations:rewrite-arconia:latest.release")
    }

    afterEvaluate {
        if (repositories.isEmpty()) {
            repositories {
                mavenCentral()
            }
        }
    }
}
----

Then, run the following command:

[source, shell]
----
./gradlew rewriteRun \
    --init-script init.gradle \
    -DactiveRecipe=io.arconia.rewrite.UpgradeArconia_0_11
----

Finally, you can remove the `init.gradle` file.

== Maven OpenRewrite Plugin

Using the https://docs.openrewrite.org[OpenRewrite Maven Plugin], you can apply the recipe to your project as follows:

[source, shell]
----
./mvnw -U org.openrewrite.maven:rewrite-maven-plugin:run \
  -Drewrite.recipeArtifactCoordinates=io.arconia.migrations:rewrite-arconia:LATEST \
  -Drewrite.activeRecipes=io.arconia.rewrite.UpgradeArconia_0_11
----
