= Upgrading Arconia

Arconia is currently in active development. We're working hard to improve it and appreciate your patience as we continue to refine the tool.

We're moving fast, and the APIs may change frequently, but we're committed to keeping the documentation up to date and making it easy to upgrade to the latest version.

We maintain an https://docs.openrewrite.org[OpenRewrite] recipe to help you upgrade your projects to the latest version of Arconia automatically. You can run it with the Arconia CLI, Gradle, or Maven as documented in the xref:_automated_upgrade[Automated Upgrade] section below.

Furthermore, make sure you check the xref:what-is-new.adoc[What's New in Arconia] page for the latest features and enhancements and the https://github.com/arconia-io/arconia/releases[release notes].

== Prerequisites

Arconia 0.30 baselines on Spring Boot 4.1. Your application must already be on Spring Boot 4.1 before you upgrade Arconia.

If your application is still on Spring Boot 4.0, upgrade it first by applying the automated https://docs.arconia.io/arconia-migrations/latest/spring/spring-boot/4-1/[Spring Boot 4.1 OpenRewrite recipes], or remain on Arconia `0.28.0` until you have migrated.

== Automated Upgrade

=== Arconia CLI

Using the https://arconia.io/docs/arconia-cli/latest/[Arconia CLI], you can upgrade your project to the latest version of Arconia:

[source,shell]
----
arconia update framework --to-version 0.30
----

=== Gradle OpenRewrite Plugin

Using the https://docs.openrewrite.org[OpenRewrite Gradle Plugin], you can apply the recipe to your project as follows.

First, create an `init.gradle` file in your Spring Boot project (root folder) with the following content:

[source,groovy]
----
initscript {
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath("org.openrewrite:plugin:latest.release")
    }
}

rootProject {
    plugins.apply(org.openrewrite.gradle.RewritePlugin)
    dependencies {
        rewrite("io.arconia.migrations:rewrite-arconia:latest.release")
    }

    // Remove when project repositories are disabled
    afterEvaluate {
        if (repositories.isEmpty()) {
            repositories {
                mavenCentral()
            }
        }
    }

    configurations.named("rewrite") {
        canBeConsumed = false
    }
}
----

Then, run the following command:

[source, shell]
----
./gradlew rewriteRun \
    --init-script init.gradle \
    --no-parallel \
    -DactiveRecipe=io.arconia.rewrite.framework.UpgradeArconia_0_30
----

Finally, you can remove the `init.gradle` file.

=== Maven OpenRewrite Plugin

Using the https://docs.openrewrite.org[OpenRewrite Maven Plugin], you can apply the recipe to your project as follows:

[source, shell]
----
./mvnw -U org.openrewrite.maven:rewrite-maven-plugin:run \
  -Drewrite.recipeArtifactCoordinates=io.arconia.migrations:rewrite-arconia:LATEST \
  -Drewrite.activeRecipes=io.arconia.rewrite.framework.UpgradeArconia_0_30
----
