[what-is-new]
= What's New in Arconia {page-component-version}

Arconia {page-component-version} provides a number of new features and enhancements. This page includes the highlights of the release, but you can also check out the full https://github.com/arconia-io/arconia/releases[release notes] for more details about each new feature and bug fix.

We provide an automated way to upgrade your project to the latest version of Arconia, which is described in the xref:upgrading-arconia.adoc[Upgrading Arconia] documentation.

== Dev Services

=== Core

* The `arconia.dev.services.startup.log-level` has been removed because redundant since Testcontainers already takes care of writing a failed container's logs to the application logs at error level.
* Registering a Dev Service now requires declaring its configuration properties with `ServiceSpec.properties()`, and `DiscoverySpec.shared()` has been removed. Whether a Dev Service is shared is read from its `shared` property. If you build your own Dev Service, add `.properties(properties)` to your registration. The automated upgrade removes the `.shared(...)` call for you. Learn more about xref:dev-services:custom-dev-services.adoc[Building Your Own Dev Service].
* A Dev Service adopted from another application now reports its links, such as management consoles and telemetry endpoints, both in the startup message and in the `devservices` actuator endpoint. Learn more about xref:dev-services:custom-dev-services.adoc#_exposing_links[Exposing Links].
