[what-is-new]
= What's New in Arconia {page-component-version}

Arconia {page-component-version} provides a number of new features and enhancements. This page includes the highlights of the release, but you can also check out the full https://github.com/arconia-io/arconia/releases[release notes] for more details about each new feature and bug fix.

We provide an automated way to upgrade your project to the latest version of Arconia, which is described in the xref:upgrading-arconia.adoc[Upgrading Arconia] documentation.

== Core

* The experimental `HostInfo` class has been removed. Use the `OsInfo` class from Spring Boot to obtain operating system information or Java's `InetAddress.getLocalHost().getHostName()` to get the hostname.

== OpenTelemetry

* OTLP exporters for logs, metrics, and traces now support setting a retry policy via configuration properties. This allows you to configure the number of retry attempts, the initial backoff duration, the maximum backoff duration, and the backoff multiplier for retrying failed export attempts. You can specify these settings globally (`arconia.otel.exporter.otlp.retry`) or for each observability signal individually (`arconia.otel.<signal>.exporter.otlp.retry`).
* The `arconia.otel.logs.logback-bridge.capture-logstash-attributes` configuration property used by the Logback Bridge has been replaced by `arconia.otel.logs.logback-bridge.capture-logstash-marker-attributes`.
