[what-is-new]
= What's New in Arconia {page-component-version}

Arconia {page-component-version} provides a number of new features and enhancements. This page includes the highlights of the release, but you can also check out the full https://github.com/arconia-io/arconia/releases[release notes] for more details about each new feature and bug fix.

We provide an automated way to upgrade your project to the latest version of Arconia, which is described in the xref:upgrading-arconia.adoc[Upgrading Arconia] documentation.

WARNING: Arconia is now based on Spring Boot 4.0. Before upgrading to this version of Arconia, an upgrade of your application to Spring Boot 4.0 is required. If you use the xref:upgrading-arconia.adoc[automated procedure], it will take care of both upgrades for you.

== Overview

* Spring Boot 4.0 is the new baseline for Arconia.

== Generative AI

* Arconia Ollama Dev Services, Arconia MongoDB Atlas Dev Services, and Arconia Docling Document Reader are based on Spring AI 2.0.0-M1. They are considered a preview until the Spring AI project releases a GA version supporting Spring Boot 4.0.
