[what-is-new]
= What's New in Arconia {page-component-version}

Arconia {page-component-version} provides a number of new features and enhancements. This page includes the highlights of the release, but you can also check out the full https://github.com/arconia-io/arconia/releases[release notes] for more details about each new feature and bug fix.

We provide an automated way to upgrade your project to the latest version of Arconia, which is described in the xref:upgrading-arconia.adoc[Upgrading Arconia] documentation.

== Overview

== Dev Services

* A new Dev Service for Valkey has been introduced, supporting Spring Boot projects integrating with REPL/Redis. Check more details about the xref:dev-services:valkey.adoc[Arconia Valkey Dev Service].

== Testcontainers

* Testcontainers modules have been introduced for Phoenix, Redis, and Valkey, supplementing the lack of support for them in the upstream project. They are the basis of the related Dev Services modules, but you can also use them directly:
** `PhoenixContainer` (`io.arconia:arconia-testcontainers-phoenix`)
** `RedisContainer` (`io.arconia:arconia-testcontainers-redis`)
** `ValkeyContainer` (`io.arconia:arconia-testcontainers-valkey`).
