[what-is-new]
= What's New in Arconia {page-component-version}

Arconia {page-component-version} provides a number of new features and enhancements. This page includes the highlights of the release, but you can also check out the full release notes for more details about each new feature and bug fix.

We provide an automated way to upgrade your project to the latest version of Arconia, which is described in the xref:upgrading-arconia.adoc[Upgrading Arconia] documentation.

== Core

* The `HostInfo.getArch()` method has been replaced by Spring Boot's `OsInfo.getArch()`.

== Dev Services

* Each Dev Service now supports a standardized `arconia.dev.services.<name>.startup-timeout` configuration property to configure the startup timeout for the service. The default value is `120s`.

== OpenTelemetry

* A new `arconia.otel.exporter.type` configuration property has been introduced to configure an exporter type for all observability signals at once. This property can be set to `otlp`, `console`, or `none`. Each observability signal can still be configured individually using the existing `arconia.otel.logs.exporter.type`, `arconia.otel.metrics.exporter.type`, and `arconia.otel.traces.exporter.type` properties.
* The `arconia-opentelemetry-sdk-spring-boot-autoconfigure` module has been renamed to `arconia-opentelemetry`.

=== Resource

* The `os.arch` and `host.arch` Resource attributes contained the same value, which is now consolidated in the `host.arch` attribute. The `os.arch` attribute has been removed.
* The experimental `container.id` and `host.id` Resource attributes have been removed from the auto-configured OpenTelemetry Resource. You can re-add them by including the `io.opentelemetry.instrumentation:opentelemetry-resources` dependency in your project and defining custom `ResourceContributor` beans populating these attributes from the `ContainerResource` and `HostIdResource` classes (in the `io.opentelemetry.instrumentation.resources` package).

=== Logs

* The `arconia.otel.logs.logs-limits` configuration property group has been renamed to `arconia.otel.logs.limits`.
* The Logback OpenTelemetry Bridge has been moved from the `arconia-opentelemetry-instrumentation-spring-boot-autoconfigure` module to the `logback-opentelemetry-bridge` module. The configuration properties for the bridge have been moved from the `arconia.otel.logs.logback-bridge` group to the `arconia.otel.logs.logback-bridge` group. If you were using the Arconia OpenTelemetry Spring Boot Starter, the new module will be automatically included in your project.

=== Metrics

* You can now enable/disable support for Exemplars via the `arconia.otel.metrics.exemplars.enabled` configuration property. This is enabled by default.
* The `arconia.otel.metrics.exemplar-filter` configuration property group has been renamed to `arconia.otel.metrics.exemplars.filter`.
* The `arconia.otel.metrics.interval` configuration property group has been renamed to `arconia.otel.metrics.export.interval`.
* The Micrometer Metrics OpenTelemetry Bridge has been moved from the `arconia-opentelemetry-instrumentation-spring-boot-autoconfigure` module to the `micrometer-metrics-opentelemetry-bridge` module. The configuration properties for the bridge have been moved from the `arconia.otel.instrumentation.micrometer` group to the `arconia.otel.metrics.micrometer-bridge.opentelemetry-api` group. If you were using the Arconia OpenTelemetry Spring Boot Starter, the new module will be automatically included in your project.

=== Traces

* Introduced new `arconia.otel.traces.processor.export-unsampled-spans` configuration property to enable exporting of unsampled spans. This is disabled by default.
* The `arconia.otel.traces.span-limits` configuration property group has been renamed to `arconia.otel.traces.limits`.
