[what-is-new]
= What's New in Arconia {page-component-version}

Arconia {page-component-version} provides a number of new features and enhancements. This page includes the highlights of the release, but you can also check out the full release notes for more details about each new feature and bug fix.

We provide an automated way to upgrade your project to the latest version of Arconia, which is described in the xref:upgrading-arconia.adoc[Upgrading Arconia] documentation.

== Core

* The `HostInfo.getArch()` method has been replaced by Spring Boot's `OsInfo.getArch()`.

== Dev Services

* Each Dev Service now supports a `arconia.dev.services.<name>.startup-timeout` configuration property to configure the startup timeout for the service. The default value is `120s`.

== OpenTelemetry

* A new `arconia.otel.exporter.type` configuration property has been introduced to configure an exporter type for all observability signals at once. This property can be set to `otlp`, `console`, or `none`. Each observability signal can still be configured individually using the existing `arconia.otel.logs.exporter.type`, `arconia.otel.metrics.exporter.type`, and `arconia.otel.traces.exporter.type` properties.
* Support for the https://opentelemetry.io/docs/specs/otel/configuration/sdk-environment-variables[OpenTelemetry Environment Variable Specification] has been improved. If both the OpenTelemetry Environment Variables and the Arconia configuration properties are set, the OpenTelemetry Environment Variables will take precedence. You can disable this support by setting the `arconia.otel.compatibility.environment-variable-specification` configuration property to `false`.
* If you'd like to migrate from the partial OpenTelemetry support in Spring Boot to the full OpenTelemetry support in Arconia, you can streamline the process by running our automated migration via OpenRewrite. See the xref:opentelemetry:migration/migration-spring-boot.adoc[dedicated migration guide] for more details.

=== Resource

* The `os.arch` and `host.arch` Resource attributes contained the same value, which is now consolidated in the `host.arch` attribute. The `os.arch` attribute has been removed.

=== Metrics

* You can now enable/disable support for Exemplars via the `arconia.otel.metrics.exemplars.enabled` configuration property. This is enabled by default.

=== Traces

* Introduced new `arconia.otel.traces.processor.export-unsampled-spans` configuration property to enable exporting of unsampled spans. This is disabled by default.
