[what-is-new]
= What's New in Arconia {page-component-version}

Arconia {page-component-version} provides a number of new features and enhancements. This page includes the highlights of the release, but you can also check out the full release notes for more details about each new feature and bug fix.

We provide an automated way to upgrade your project to the latest version of Arconia, which is described in the xref:upgrading-arconia.adoc[Upgrading Arconia] documentation.

== Dev Services

* The documentation about the Arconia Dev Services has been improved and extended, including special instructions for using them in a Maven project.

== Docling

* The Docling Dev Service has been updated to use Docling Serve 1.3, and support has been extended for images from both GitHub Container Registry (`ghcr.io/docling-project/docling-serve`) and Quay.io (`quay.io/docling-project/docling-serve`). By default, the Dev Service will use the GitHub Container Registry image.
* The Docling Dev Service supports a configuration property, `arconia.dev.services.docling.enable-ui`, which allows you to enable or disable the Docling UI. Unlike previous versions, this property is now only considered when running the application in dev mode.
