= Arconia Dev Tools

Arconia Dev Tools is a collection of tools that help you develop and test your Spring Boot applications more efficiently, with a special focus on improving your developer experience.

== Dependencies

First, you need to add the Arconia Dev Tools dependency to your project.

[source,groovy]
----
dependencies {
  testAndDevelopmentOnly 'io.arconia:arconia-dev-tools'
}
----

== Tools

=== Profiles

Arconia Dev Tools include a set of default profiles for conveniently providing custom configuration when running the application in development mode or when running tests. See xref:profiles.adoc[Profiles] for more information.

=== Spring Boot DevTools

Arconia Dev Tools include the Spring Boot Developer Tools. Among the other things, these tools provide a feature which automatically restarts your application when you make changes to your code as part of your development workflow. Refer to the https://docs.spring.io/spring-boot/reference/using/devtools.html[official documentation] to learn more about the different tools, how they work, and their limitation.
