= Profiles

When working with Spring Boot applications, it's common to define specific configurations for different environments, such as development, testing, and production. Spring Boot provides a powerful way to manage these configurations using https://docs.spring.io/spring-boot/reference/features/profiles.html[profiles].

Even more common is to have custom configuration when running the application in development mode or when running tests, to the point that it's almost boilerplate code to define these configurations in each project. Arconia aims at improving the developer experience on top of Spring Boot, which is why it provides that out of the box.

By default, the Arconia Dev Tools library provides two profiles that are enabled automatically in certain conditions:

* `dev`: Enabled when running the application in development mode (e.g. `./gradlew bootRun` or `./mvnw spring-boot:run).
* `test`: Enabled when running tests or when running the application in test mode (e.g. `./gradlew bootTestRun` or `./mvnw spring-boot:test-run`).

== Enabling/Disabling Profiles

Arconia profiles are enabled by default. You can disable them via configuration properties.

[source,yaml]
----
arconia:
  dev:
    profiles:
      enabled: false
----

== Configuration Properties

Each organization may have its own set of custom profiles to manage development and testing environments. For example, instead of having a `dev` profile, you may have a `local` profile where you define the configuration for your local development environment. That's why Arconia makes these profiles configurable.

.Profiles Configuration Properties
|===
|Property |Default |Description
|	`arconia.dev.profiles.development`
|	`dev`
|	Name of the development profiles.

|	`arconia.dev.profiles.test`
|	`test`
|	Name of the test profiles.
|===

Both properties accept a list of profiles. For example, you can define multiple profiles to be activated when running tests:

[source,yaml]
----
arconia:
  dev:
    profiles:
      test: dev, test
----
