create table tenant_details
(
    id         integer generated by default as identity primary key,
    identifier varchar(255) default cast(random_uuid() as varchar) not null unique,
    enabled    boolean default true not null,
    created_at timestamp default now() not null
);

create table tenant_details_attributes
(
    tenant_id       integer not null references tenant_details (id),
    attribute_name  varchar(255) not null,
    attribute_value varchar(255) not null,
    primary key (tenant_id, attribute_name)
);
