package io.arconia.docling.client.convert.request.options;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Type of response generated by the model.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public enum ResponseFormat {

    @JsonProperty("doctags")
    DOCTAGS,
    @JsonProperty("markdown")
    MARKDOWN,
    @JsonProperty("html")
    HTML,
    @JsonProperty("otsl")
    OTSL,
    @JsonProperty("plaintext")
    PLAINTEXT

}
