plugins {
    id "code-quality-conventions"
    id "java-conventions"
    id "sbom-conventions"
    id "release-conventions"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

dependencies {
    api project(":arconia-core")
    api project(":arconia-multitenancy:arconia-multitenancy-core")
    api "org.springframework.boot:spring-boot-jdbc"

    testImplementation "org.springframework.boot:spring-boot-starter-test"
    testRuntimeOnly "com.h2database:h2"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            pom {
                name = "Arconia Multitenancy Data JDBC"
                description = "Arconia Multitenancy Data JDBC."
            }
        }
    }
}
