version = 1

[install]
jbang.pkg-path = "jbang"
httpie.pkg-path = "httpie"

[vars]
FLOX_DISABLE_METRICS="true"

[hook]
on-activate = """
  eval $(jbang jdk env 24)
"""

[profile]

[services]

[include]

[options]
systems = [
  "aarch64-darwin",
  "aarch64-linux",
  "x86_64-darwin",
  "x86_64-linux",
]
