schema-version = "1.12.0"

[install]
graalvm-ce.pkg-path = "graalvmPackages.graalvm-ce"

[vars]
FLOX_DISABLE_METRICS = "true"

[hook]

[profile]

[services]

[include]

[build]

[options]
systems = ["aarch64-darwin", "aarch64-linux", "x86_64-linux"]
