= Grafana LGTM
:service-name: lgtm

When your application uses OpenTelemetry for observability, you can use the OpenTelemetry LGTM Dev Service to start automatically a Grafana observability platform based on OpenTelemetry. This enables you to visualize and explore your application's telemetry data during development and testing.

== Dependencies

include::partial$dependencies.adoc[]

== Running the Application

include::partial$running-application.adoc[]

By default, the Dev Service will be reused across multiple applications, useful for reducing resource consumption, speeding up the startup time, and enabling observability across multiple applications.

== Accessing Grafana

The application logs will show you the URL where you can access the Grafana observability platform and information about logs, metrics, and traces being exported to the platform.

[source,logs]
----
...o.t.grafana.LgtmStackContainer           : Access to the Grafana dashboard: http://localhost:38125
...s.l.e.o.OtlpLoggingExporterConfiguration : Configuring OpenTelemetry HTTP/Protobuf log exporter with endpoint: http://localhost:39117/v1/logs
...s.m.e.o.OtlpMetricsExporterConfiguration : Configuring OpenTelemetry HTTP/Protobuf metric exporter with endpoint: http://localhost:39117/v1/metrics
...s.t.e.o.OtlpTracingExporterConfiguration : Configuring OpenTelemetry HTTP/Protobuf span exporter with endpoint: http://localhost:39117/v1/traces
----

By default, logs, metrics, and traces are exported via OTLP using the HTTP/Protobuf format.

== Customizing the Dev Service

You can customize the Dev Service via configuration properties, such as changing the image name or not reusing the service across multiple applications.

[source,yaml]
----
arconia:
  dev:
    services:
      lgtm:
        image-name: grafana/otel-lgtm
        reusable: true
        environment:
          ENABLE_LOGS_ALL: "true"
----

== Disabling the Dev Service

include::partial$disabling-dev-service.adoc[]
