= Grafana LGTM
:service-name: lgtm

A service providing a Grafana LGTM observability platform based on OpenTelemetry for development and testing purposes. It consists of:

* https://grafana.com/oss/grafana[Grafana] for visualizing and exploring telemetry data.
* https://opentelemetry.io/docs/collector[OpenTelemetry Collector] for collecting telemetry data from your application using OTLP.
* https://grafana.com/oss/loki[Grafana Loki] for storing and querying logs.
* https://prometheus.io[Prometheus] for storing and querying metrics.
* https://grafana.com/oss/tempo[Grafana Tempo] for storing and querying traces.

It works with Spring Boot libraries that support OpenTelemetry, including:

* xref:opentelemetry:index.adoc[Arconia OpenTelemetry].

[NOTE]
====
The Dev Service for Grafana LGTM is mutually exclusive with the Dev Service for xref:otel-collector.adoc[OpenTelemetry Collector] and xref:phoenix.adoc[Arize Phoenix], as they all integrate with OpenTelemetry. If more than one of those Dev Services is included in the project dependencies, ensure you only enable one of them via configuration properties (`arconia.dev.services.<name>.enabled`).
====

== Dependencies

include::partial$dependencies.adoc[]

== Running the Application

include::partial$running-application.adoc[]

By default, when running the application in development mode, the Dev Service will be shared across multiple applications.

== Accessing Grafana

The application logs will show you the URL where you can access the Grafana observability platform and information about logs, metrics, and traces being exported to the platform.

[source,logs]
----
...o.t.grafana.LgtmStackContainer           : Access to the Grafana dashboard: http://localhost:38125
...s.l.e.o.OtlpLoggingExporterConfiguration : Configuring OpenTelemetry HTTP/Protobuf log exporter with endpoint: http://localhost:39117/v1/logs
...s.m.e.o.OtlpMetricsExporterConfiguration : Configuring OpenTelemetry HTTP/Protobuf metric exporter with endpoint: http://localhost:39117/v1/metrics
...s.t.e.o.OtlpTracingExporterConfiguration : Configuring OpenTelemetry HTTP/Protobuf span exporter with endpoint: http://localhost:39117/v1/traces
----

By default, logs, metrics, and traces are exported via OTLP using the HTTP/Protobuf format.

== Configuring the Dev Service

You can configure the Dev Service via configuration properties.

|===
|Property |Default |Description

|`arconia.dev.services.lgtm.enabled`
| `true`
| Whether the dev service is enabled.

|`arconia.dev.services.lgtm.image-name`
| `grafana/otel-lgtm`
| Full name of the container image used in the dev service.

|`arconia.dev.services.lgtm.environment`
| `{}`
| Environment variables to set in the container. Example: `ENABLE_LOGS_ALL: "true"`.

|`arconia.dev.services.lgtm.shared`
| `dev-mode`
| When the container used in the dev service is shared across applications.

| `arconia.dev.services.lgtm.startup-timeout`
| `120s`
| Maximum waiting time for the service to start.
|===

include::partial$disabling-dev-service.adoc[]
