= Ollama Dev Service
:service-name: ollama

When your application uses Spring AI to consume large language models from Ollama, you can use the Ollama Dev Service to start automatically an Ollama service. This enables you to develop and test your LLM-powered application without having to manually provide a model inference service.

== Dependencies

include::partial$dependencies.adoc[]

=== Enabling the Dev Service

By default, the Ollama Dev Service is disabled since it might be resource-intensive, and running native Ollama might be more suitable for development. You can enable it globally or selectively for specific tests.

[source,yaml]
----
arconia:
  dev:
    services:
      ollama:
        enabled: true
----

You can enable/disable the Dev Service for a specific application mode (development, test, production), relying on one of the profiles which are automatically configured by Arconia (see xref:ROOT:core-features/profiles.adoc[Profiles]).

TIP: You can enable/disable the Dev Service for a specific test class by using the `@TestProperty` annotation or equivalent Spring testing utilities.

== Running the Application

include::partial$running-application.adoc[]

== Customizing the Dev Service

You can customize the Dev Service via configuration properties, such as changing the image name or not reusing the service across multiple applications.

[source,yaml]
----
arconia:
  dev:
    services:
      ollama:
        image-name: ollama/ollama
        reusable: true
        environment:
          OLLAMA_NUM_PARALLEL: "4"
----
