= Redis Dev Service
:service-name: redis

When your application needs a Redis data store (such as when using Spring Data Redis or Spring AI Redis Vector Store), you can use the Redis Dev Service to automatically start a Redis server. This enables you to develop and test your application without having to manually start and manage the Redis server.

== Dependencies

include::partial$dependencies.adoc[]

== Running the Application

include::partial$running-application.adoc[]

== Choosing the Redis Edition

By default, the Redis Dev Service enables the Community Edition of Redis, but you can also activate the Stack Edition if you need to.

[source,yaml]
----
arconia:
  dev:
    services:
      redis:
        edition: stack
----

== Customizing the Dev Service

You can customize the Dev Service via configuration properties, such as changing the image name or not reusing the service across multiple applications.

For Redis Community:

[source,yaml]
----
arconia:
  dev:
    services:
      redis:
        community:
          image-name: redis
          reusable: false
          environment:
            REDIS_PASSWORD: redis
----

For Redis Stack:

[source,yaml]
----
arconia:
  dev:
    services:
      redis:
        stack:
          image-name: redis/redis-stack-server
          reusable: false
          environment:
            REDIS_PASSWORD: redis
----

== Disabling the Dev Service

include::partial$disabling-dev-service.adoc[]
