plugins {
    id "code-quality-conventions"
    id "java-conventions"
    id "sbom-conventions"
    id "release-conventions"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

dependencies {
    annotationProcessor "org.springframework.boot:spring-boot-autoconfigure-processor"
    annotationProcessor "org.springframework.boot:spring-boot-configuration-processor"

    api project(":arconia-core")
    api project(":arconia-multitenancy:arconia-multitenancy-core")
    api "org.springframework.boot:spring-boot-jdbc"

    optional "org.springframework.boot:spring-boot-autoconfigure"
    optional "org.springframework.boot:spring-boot-health"

    testImplementation "org.springframework.boot:spring-boot-starter-test"
    testImplementation "org.testcontainers:testcontainers-junit-jupiter"
    testImplementation "org.testcontainers:testcontainers-postgresql"
    testRuntimeOnly "com.h2database:h2"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
    testRuntimeOnly "org.postgresql:postgresql"
}

dependencyManagement {
    dependencies {
        dependency "org.postgresql:postgresql:42.7.13"
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            pom {
                name = "Arconia Multitenancy TenantDetails JDBC"
                description = "Arconia Multitenancy TenantDetails JDBC"
            }
        }
    }
}
