= OpenTelemetry Dev Services

Arconia Dev Services provide a zero-code integration to services your application depends on, both at development and test time, relying on the power of Testcontainers and Spring Boot. This page describes the Arconia Dev Service for OpenTelemetry.

NOTE: For more information, see the xref:../../dev-services/introduction.adoc[Dev Services] page.

== Grafana LGTM

When your application uses OpenTelemetry for observability, you can use the Arconia OpenTelemetry LGTM Dev Service to automatically start a full Grafana observability platform based on OpenTelemetry. This enables you to visualize and explore your application's telemetry data during development and testing.

=== Dependencies

First, you need to add the Arconia OpenTelemetry LGTM Dev Service dependency to your project.

[source,groovy]
----
dependencies {
  testAndDevelopmentOnly 'io.arconia:arconia-dev-service-opentelemetry-lgtm'
}
----

TIP: This dependency also includes the https://docs.spring.io/spring-boot/reference/using/devtools.html[Spring Boot DevTools], which automatically restarts your application when you make changes to your code as part of your development workflow.

=== Running the Application

Unlike the lower-level Testcontainers support in Spring Boot, Arconia doesn't require special tasks to run your application (`./gradlew bootTestRun` or `./mvnw spring-boot:test-run`). You can simply use:

* Gradle: `./gradlew bootRun`
* Maven: `./mvnw spring-boot:run`

Your integration tests will automatically use the Arconia Dev Services without any additional configuration.

NOTE: Whenever the application is reloaded via Spring Boot DevTools, the Dev Service will not be restarted. If you want to disable the live reload feature, you can do so by setting the `spring.devtools.restart.enabled` property to `false`. When doing so, the Dev Service will be shut down and restarted along with the application.

The application logs will show you the URL where you can access the Grafana observability platform and information about logs, metrics, and traces being exported to the platform.

[source,logs]
----
...o.t.grafana.LgtmStackContainer           : Access to the Grafana dashboard: http://localhost:38125
...s.l.e.o.OtlpLoggingExporterConfiguration : Configuring OpenTelemetry HTTP/Protobuf log exporter with endpoint: http://localhost:39117/v1/logs
...s.m.e.o.OtlpMetricsExporterConfiguration : Configuring OpenTelemetry HTTP/Protobuf metric exporter with endpoint: http://localhost:39117/v1/metrics
...s.t.e.o.OtlpTracingExporterConfiguration : Configuring OpenTelemetry HTTP/Protobuf span exporter with endpoint: http://localhost:39117/v1/traces
----

By default, logs, metrics, and traces are exported via OTLP using the HTTP/Protobuf format.

=== Customizing the Dev Service

You can customize the Dev Service via configuration properties, such as changing the image name or not reusing the service across multiple applications and tests.

[source,yaml]
----
arconia:
  dev:
    services:
      lgtm:
        image-name: grafana/otel-lgtm:0.8.6
        reusable: false
----

=== Disabling the Dev Service

If you want to disable the Dev Service, you can do so via configuration properties.

[source,yaml]
----
arconia:
  dev:
    services:
      lgtm:
        enabled: false
----

TIP: You can disable the Dev Service for a specific test class or method by using the `@TestProperty` annotation or equivalent Spring testing utilities.

Alternatively, you can disable it by excluding the auto-configuration class directly: `LgtmDevServiceAutoConfiguration`.
