= Arconia OpenTelemetry
:description: Learn how to get started with Arconia OpenTelemetry for Spring Boot applications.

Arconia provides unified observability for Spring Boot applications, combining full support for OpenTelemetry API, SDK, and Instrumentation while also providing a seamless integration with Micrometer API and Instrumentation. The goal is to provide a single, unified observability solution for Spring Boot applications that can give you the best of both worlds: the standardization and ubiquity of OpenTelemetry and the robustness and stability of Micrometer.

== Quick Start

Let's see how you can get started with Arconia OpenTelemetry in your Spring Boot application.

=== Dependencies

If you already have a Spring Boot application and want to add OpenTelemetry support, you can add the Arconia OpenTelemetry Spring Boot Starter dependency to your project. This will automatically configure OpenTelemetry, Micrometer, and Spring Boot Actuator for you. 

[source,groovy]
----
dependencies {
  implementation 'io.arconia:arconia-opentelemetry-spring-boot-starter'
}
----

Arconia publishes a BOM (Bill of Materials) that you can use to manage the version of the Arconia OpenTelemetry Spring Boot Starter. Whether not required, it is recommended to use the BOM to ensure that all dependencies are compatible.

[source,groovy,subs="attributes"]
----
dependencyManagement {
	imports {
		mavenBom "io.arconia:arconia-bom:{page-component-version}"
	}
}
----

=== Dev Service

Building on top of Spring Boot support for Testcontainers, Arconia provides zero-code dev services for a superior developer experience. When working with OpenTelemetry, you can use the Arconia OpenTelemetry Dev Service LGTM to automatically start a full Grafana observability platform based on OpenTelemetry, giving you the possibility to visualize and explore your application's telemetry data during development and testing.

To enable the Arconia OpenTelemetry Dev Service LGTM, you can add the following dependency to your project.

[source,groovy]
----
dependencies {
	testAndDevelopmentOnly 'io.arconia:arconia-dev-service-opentelemetry-lgtm'
}
----

=== Running the Application

Once you have added the dependencies, you can run your Spring Boot application using the Spring Boot plugins for Gradle or Maven. Unlike the lower level Testcontainers support in Spring Boot, with Arconia you don't need special tasks to run your application in order to benefit from the dev services (e.g. `./gradlew bootTestRun`). You can simply run your application as usual.

[source,shell]
----
./gradlew bootRun
----

The application logs will show you the URL where you can access the Grafana observability platform and information about logs, metrics, and traces being exported to the platform.

[source,logs]
----
... Access to the Grafana dashboard: http://localhost:38125
... Configuring OpenTelemetry HTTP/Protobuf log exporter with endpoint: http://localhost:39117/v1/logs
... Configuring OpenTelemetry HTTP/Protobuf metric exporter with endpoint: http://localhost:39117/v1/metrics
... Configuring OpenTelemetry HTTP/Protobuf span exporter with endpoint: http://localhost:39117/v1/traces
----

By default, logs, metrics, and traces are exported via OTLP using the HTTP/Protobuf format.

== Next Steps

Now that you have successfully set up Arconia OpenTelemetry in your Spring Boot application, you can explore the various features and capabilities of the framework. Keep reading the documentation to learn more about how to configure and customize OpenTelemetry and Micrometer for your Spring Boot applications.
